sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
script:
  - npm run fetch-dataset
  - npm run build-html-prod
before_deploy:
  - npm i now --no-save
deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true
  on:
    branch: master
# after_deploy:
#   - npm run clean-deploys
env:
  matrix:
    - INSTANCE_NAME='acamica-dwfs-belgrano'
